name: CI Pipeline for Python Package

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Package
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
                  cache: "pip"
                  cache-dependency-path: "**/setup.py"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: "Check packages"
              run: |
                  python -m pip install -U setuptools wheel twine
                  python setup.py sdist bdist_wheel
                  python -m twine check --strict dist/*

    test:
        needs: build
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.6", "3.8", "3.9", "3.10", "3.11"]
                os:
                    - macos-latest
                    - windows-latest
                    - ubuntu-latest

        runs-on: ${{ matrix.os }}
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install pytest

            - name: Test with pytest
              run: |
                  pytest
